* homebrew-emacs

#+begin_html
<p align="left">
  <a href="https://github.com/miles170/homebrew-emacs/actions/workflows/tests.yml">
    <img src="https://github.com/miles170/homebrew-emacs/actions/workflows/tests.yml/badge.svg" alt="CI Status Badge" />
  </a>
</p>
#+end_html

This is a third party tap for [[https://brew.sh/][Homebrew]]. It provides a formula for =emacs= which includes options for enabling additional features.

*Note: This formula builds only Linux platforms.*

** Installation and usage

In order to use this tap, you need to install Homebrew.

Then, to run a default installation, run:

#+begin_src bash
brew tap miles170/emacs
brew install miles170/emacs/emacs --with-native-comp
#+end_src

*** Options

| Option               | Description                   |
|----------------------|-------------------------------|
| =--with-native-comp= | build with native compilation |

** Issues

To report issues, please [[https://github.com/miles170/homebrew-emacs/issues][file an issue on GitHub]]. Please include the full command line you have tested and the full terminal output you got with. Please note that we will only be able to help with issues that are exclusive to this tap and for OS which are officially supported.

If the problem is reproducible with the =homebrew-core= version of =emacs=, please file it [[https://github.com/Homebrew/homebrew-core/][on their tracker]].
