name: CI

on:
  push:
    branches:
      - main
    paths:
      - "Formula/emacs.rb"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "Formula/emacs.rb"
      - ".github/workflows/tests.yml"

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  cancel_previous_runs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot --skip-recursive-dependents Formula/emacs.rb

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        build_opts:
          - "--with-native-comp"
          - "--with-json"
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build emacs ${{ matrix.build_opts }}
        run: brew install Formula/emacs.rb ${{ matrix.build_opts }}

      - name: Test installation
        run: |
          brew test Formula/emacs.rb
          [[ '${{ matrix.build_opts }}' == '--with-native-comp' ]] && test=native-comp-available-p
          [[ '${{ matrix.build_opts }}' == '--with-json' ]] && test=json-available-p
          $(brew --prefix)/bin/emacs --batch --eval="(unless (${test}) (error (kill-emacs 1)))"
