name: CI

on:
  push:
    branches:
      - main
    paths:
      - "Formula/emacs.rb"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "Formula/emacs.rb"
      - ".github/workflows/tests.yml"

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-bot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/brew:main
      options: --privileged
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@a657b8b0cd35d0f65cce41fce9b24cf054b49869 # 2026.08.24.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ubuntu-latest-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ubuntu-latest-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae --skip-dependents
