name: CI

on:
  push:
    branches:
      - main
    paths:
      - "Formula/emacs.rb"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "Formula/emacs.rb"
      - ".github/workflows/tests.yml"

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  cancel_previous_runs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          test-bot: true

      - run: brew test-bot --skip-dependents --build-from-source Formula/emacs.rb

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        build_opts:
          - ""
          - "--with-native-comp"
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build emacs ${{ matrix.build_opts }}
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: "1"
        run: brew install Formula/emacs.rb ${{ matrix.build_opts }}

      - name: Test installation
        run: brew test Formula/emacs.rb
